### ISSUE TITLE
APIManagerAPIAdapter keeps old parameters

### ISSUE THREAD

**Issue by matthias-franke** [Axway-API-Management-Plus/apim-cli#293]
### APIM-CLI version

1.12.0

### API-Management version

7.7

### Bug description

We are using apim-cli in our Java-Project:
```
  <dependency>
	  <groupId>com.github.axway-api-management-plus.apim-cli</groupId>
	  <artifactId>apimcli-apis</artifactId>
	  <version>1.2.1</version>
  </dependency>
```

Accordingly, 
   APIExportApp.exportAPI(cmdArgs); 
can be called multiple times.
but APIManagerAPIAdapter retains parameters of the first call to exportAPI(cmdArgs).
So the request to /api/portal/v1.1/proxies/ is sent to the wrong Host (parameter from the first call):
![invalid export session](https://user-images.githubusercontent.com/6809646/178006693-6556b5da-f3b6-4b7b-bf2c-0ed8c3a42f77.jpg)

cause is obvious:
**APIManagerAPIAdapter.cmd** is only initialized once when loading the class.
cmd is never updated. Its used for every new export ( See usage of **cmd** in "getAPIRequestUri(APIFilter filter)" ):

```
public class APIManagerAPIAdapter {
...
	static CoreParameters cmd = CoreParameters.getInstance();
...
	URI getAPIRequestUri(APIFilter filter) throws URISyntaxException, AppException {		
		...
		URI uri = new URIBuilder(cmd.getAPIManagerURL())....
```

Parameters stored in a Singleton, static reference to Singleton, reference not updated.
Maybe APIManagerAPIAdapter is not the only place where this is done.

Once the problem with the invalid state in the Library is solved...
Feature request 1: The library should be thread-safe
Feature request 2: The library should support multithreading

**Comment by matthias-franke** [comment]
as mentioned above:
"APIExportApp.exportAPI(cmdArgs);
can be called multiple times."

e.g.:
```
String cmd1 = "api get -h " + host1 + " -port " + 8075 + " -u " + user1 + " -p " + pass1 + " -id " + id1 + " --target " + folder1 + " -o json -deleteTarget";
String[] cmdArgs1 = cmd1.split(" ");
APIExportApp.exportAPI(cmdArgs1);

String cmd2 = "api get -h " + host2 + " -port " + 8075 + " -u " + user2 + " -p " + pass2 + " -id " + id2 + " --target " + folder2 + " -o json -deleteTarget";
String[] cmdArgs2 = cmd2.split(" ");
APIExportApp.exportAPI(cmdArgs2);	
```

**Comment by matthias-franke** [comment]
to reproduce multiple calls to "APIExportApp.exportAPI(cmdArgs)" you have to use-the-cli-java-apis-in-your-java-application (https://github.com/Axway-API-Management-Plus/apim-cli/wiki/1.-How-to-get-started#use-the-cli-java-apis-in-your-java-application)

**Comment by rathnapandi** [comment]
Hi @matthias-franke, 

As a workaround can you call APIManagerAdapter.deleteInstance() before the second call? which will recreate a API Manager session with new host and credentials. 

e.g

String cmd1 = "api get -h " + host1 + " -port " + 8075 + " -u " + user1 + " -p " + pass1 + " -id " + id1 + " --target " + folder1 + " -o json -deleteTarget";
String[] cmdArgs1 = cmd1.split(" ");
APIExportApp.exportAPI(cmdArgs1);

String cmd2 = "api get -h " + host2 + " -port " + 8075 + " -u " + user2 + " -p " + pass2 + " -id " + id2 + " --target " + folder2 + " -o json -deleteTarget";
String[] cmdArgs2 = cmd2.split(" ");
APIManagerAdapter.deleteInstance();
APIExportApp.exportAPI(cmdArgs2);

**Comment by matthias-franke** [comment]
have you tried it yourself before giving advice?
I did!
I spent an extremely long time dealing with the problem.
I explained:
"...static CoreParameters cmd = CoreParameters.getInstance();
Parameters stored in a Singleton, static reference to Singleton, reference not updated..."

APIManagerAdapter.deleteInstance() cannot cause the APIManagerAPIAdapter class to be reloaded and the new parameters to appear in cmd. cmd is static! It is used in getAPIRequestUri.

why can't you see this?

**Comment by cwiechmann** [comment]
The framework is currently not designed to support this use-case to communicate with multiple API-Manager instances for a number of reasons. And it would be a tremendous effort to add support for it.

I'm afraid to say, that you have to look for another approach.

**Comment by cwiechmann** [comment]
You can use it to communicate with a single API-Manager instance in your application, but not with multiple ones. Hence, the page is still valid IMHO.

**Comment by matthias-franke** [comment]
IMO when you offer a library, expect your public methods to be called with variable parameters. Expect to be multithreaded.

**Comment by cwiechmann** [comment]
I agree with you the design might be better to support this use-case, but the tool has been created with a different focus in mind and making use of the Java-API is some kind of a side-product.

**Comment by matthias-franke** [comment]
apart from design (parameters in Singleton ...):
wouldn't you say that
"static CoreParameters cmd = CoreParameters.getInstance();" in APIManagerAPIAdapter is a bug?
Remove it and the compiler will force you to insert the line "CoreParameters cmd = CoreParameters.getInstance();" in the method "getAPIRequestUri". This way you use the Singleton normally: get the instance when it's needed, not just once when the class is loaded - 
when the class is loaded can change quickly...
Let's face it: At the moment, it's just a matter of luck that the parameters are already filled when the class is loaded

**Comment by rathnapandi** [comment]
Sorry!! @matthias-franke. 

The issue is fixed and tested by removing the static block. 
Can you test the fix?

Binary download: 
[axway-apimcli-1.12.2-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apim-cli/files/9152265/axway-apimcli-1.12.2-SNAPSHOT.tar.gz)

Build from source:
1. checkout develop branch
2. Build maven project - mvn install -Dmaven.test.skip=true
3. Change apim-cli version on the consuming java application. 

      <dependency>
            <groupId>com.github.axway-api-management-plus.apim-cli</groupId>
            <artifactId>apimcli-apis</artifactId>
            <version>1.12.2-SNAPSHOT</version>
        </dependency>

**Comment by rathnapandi** [comment]
Sorry!! @matthias-franke. 

The issue is fixed and tested by removing the static block. 
Can you test the fix?

Binary download: 
[axway-apimcli-1.12.2-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apim-cli/files/9152265/axway-apimcli-1.12.2-SNAPSHOT.tar.gz)

Build from source:
1. checkout develop branch
2. Build maven project - mvn install -Dmaven.test.skip=true
3. Change apim-cli version on the consuming java application. 

      <dependency>
            <groupId>com.github.axway-api-management-plus.apim-cli</groupId>
            <artifactId>apimcli-apis</artifactId>
            <version>1.12.2-SNAPSHOT</version>
        </dependency>

**Comment by matthias-franke** [comment]
COOL!
you made my day!
Will not be able to test soon, since I still can't clone a github-project (firewall). I will try to download src... but probably can't build your project (our company-mvn-repo often doesn't have all needed dependencies..., proxy to mvn-central is not open)
let's see!
THANKS

**Comment by rathnapandi** [comment]
fixed in v 1.12.2
