### ISSUE TITLE
"apim api change" command hangs without output

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#84]
**API-Mgr. CLI version**
1.2.2

**API-Manager and Service-Pack Version**
7.6.2 SP4
7.7.20200730

**Expected behavior**
backend should be changed

**Actual behavior**
If I run as an OrgAdmin the command "apim api change -id <proxyId> -s <myStage> -newBackend https://new.backend.host.675/api -oldBackend http://petstore.swagger.io/v1" the cli only connects successfully to API Manager, nothing else.
The terminal hangs now for minutes without any output.

**Log-Output in Debug**
----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.2

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.2.2)
----------------------------------------------------------------------------------------
2363   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://...:8075

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
@jschaefer77, can you please re-run with debug enabled? 
https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug
Thanks!

**Comment by jschaefer77** [comment]
Hi @cwiechmann, it is the same behavior even with debug enabled. Should there be a log file somewhere?
I tried it with OrgAdmin and API Manager admin. But still the same behavior.

**Comment by cwiechmann** [comment]
Debug will just print more DEBUG messages along with the standard INFO message. No extra file for that. So, the CLI is basically stopping right at the beginning.

I'm wondering about the call you made:
`apim api change -id -s -newBackend https://new.backend.host.675/api -oldBackend http://petstore.swagger.io/v1`
I assume you have removed that information for security reasons.

I'm afraid we need a Web-Session to figure out was it going on.

**Comment by jschaefer77** [comment]
Hi @cwiechmann,
you are right, if I run the command there will be an id and a stage.

**Comment by cwiechmann** [comment]
@jschaefer77, I have just released version 1.2.3 of the CLI as a number of pending fixes/changes required a new release anyway. I also fixed an issue for the change command. If you find the time, can you please re-test with the newest version? Thanks!
Can you please test without an https:// URL for the new backend?

**Comment by jschaefer77** [comment]
Hi @cwiechmann, I did a re-test with version 1.2.3. Still the same behavior.

**Comment by cwiechmann** [comment]
Hi @jschaefer77, I would like to figure out what is happening with this command on your side as the release date for 1.3.0 comes closer and I would like to have this fixed.
Can you please retry with the most recent build from here and if it's still not working, can you please retry with [debug](https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug) enabled. 

[axway-apimcli-1.3.0-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/5480369/axway-apimcli-1.3.0-SNAPSHOT.zip)

This release already contains other [features included in the next release](https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/CHANGELOG.md). Feel free to test & provide feedback.

**Comment by cwiechmann** [comment]
@jschaefer77, sorry to ask you again, but as I have just fixed another issue in that area and it was working okay I would like to close this issue now.
If you come across this issue again (perhaps with the coming version 1.3.4) we should have a Websession as I would like to see it and if needed we can reopen this issue.

**Comment by jschaefer77** [comment]
Hi @cwiechmann . I will do a test with version 1.3.4 and let you know the result.
